os:
    - linux
language: node_js
node_js:
    - "7.8.0"
before_install:
    - npm install -g npm
    - npm install -g yarn
install:
    - yarn install
    - yarn link
script:
    - gulp eslint
    - gulp test
